sudo: false
language: node_js
node_js:
  - "0.10"
after_success:
  - rm dist/*
  - grunt compile
  - tar cvf ./knockout.validation.travis.tar.gz dist/*
  - curl -i -F name=knockout.validation.travis.tar.gz -F file=@knockout.validation.travis.tar.gz https://uguu.se/api.php?d=upload-tool
